/**
 * Firebase web config for PastaPresto.
 *
 * These values are NOT secret - Firebase web config is designed to ship to the
 * browser, and every visitor can read it. What protects your data is
 * firestore.rules, not this file.
 *
 * Generated by scripts/write-firebase-config.js. Re-run it to re-sync.
 */
export const firebaseConfig = {
  apiKey: "AIzaSyBX0I6kPkRB5Z2SOyKhZ9S43oKrGsGm1lc",
  authDomain: "pastapronto-260909.firebaseapp.com",
  projectId: "pastapronto-260909",
  storageBucket: "pastapronto-260909.firebasestorage.app",
  messagingSenderId: "256353476635",
  appId: "1:256353476635:web:f4d1d784a2904d2772d8be",
};

/** True once real values are in place, so screens can show a helpful message. */
export const isConfigured = !Object.values(firebaseConfig).some(
  (v) => typeof v === 'string' && v.includes('REPLACE_ME'),
);
